### ISSUE TITLE
感谢！mac用11.0打不开burp（主要是激活工具run不起来），只能用8.0，求解？

### ISSUE THREAD

**Issue by UCHAMDRA** [undefinedsec/HaE-Java#1]
感谢！mac用11.0打不开burp（主要是激活工具run不起来），只能用8.0，求解？

**Comment by undefinedsec** [comment]
Java版本已降低为"1.7.0_80"，请用https://github.com/undefinedsec/HaE-Java/releases/tag/v0.4重试。
